name: image-caption
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip:
      - scikit-image
      - matplotlib
      - ipykernel
      - numpy
      - nltk
      - torch
      - torchvision
      - pycocotools