[tool.black]
line-length = 87
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tmp
  | \.vscode
  | \.*.egg-info
)/
'''

[tool.isort]
profile = 'black'
multi_line_output = 3
